### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by othyn** [othyn/pub-golf#1]
- [ ] Migrate to VueJS
- [ ] Look to implement web sockets instead of micro-API calls
- [ ] Split out commonly used form fields into Blade/Vue components
